### ISSUE TITLE
Possible problem when handling state on distributed applications

### ISSUE THREAD

**Issue by ecamalionte** [Finbits/pluggy_elixir#4]
# Problem
The client is using an agent to hold the Auth **state**. 
This issue documents the problem with managing state when the client has a distributed env such as the picture below.

![image](https://user-images.githubusercontent.com/624009/116104980-45fdf880-a687-11eb-8db6-5d2e96cfdfbf.png)

# Solution

- [ ] test Pluggy to understand the behaviour creating two api_keys
- [ ] document the result and possible problems in distributed envs

**Comment by fernandoalmeida** [comment]
We tested and concluded that generating multiple API keys does not have influence among them. All keys continue working successfully.
